// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gridnode/dispensation/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_x_bank_types "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateDistribution struct {
	Distributor      string                                             `protobuf:"bytes,1,opt,name=distributor,proto3" json:"distributor,omitempty"`
	AuthorizedRunner string                                             `protobuf:"bytes,2,opt,name=authorized_runner,json=authorizedRunner,proto3" json:"authorized_runner,omitempty"`
	DistributionType DistributionType                                   `protobuf:"varint,3,opt,name=distribution_type,json=distributionType,proto3,enum=gridnode.dispensation.v1.DistributionType" json:"distribution_type,omitempty"`
	Output           []github_com_cosmos_cosmos_sdk_x_bank_types.Output `protobuf:"bytes,4,rep,name=output,proto3,customtype=github.com/cosmos/cosmos-sdk/x/bank/types.Output" json:"output,omitempty"`
}

func (m *MsgCreateDistribution) Reset()         { *m = MsgCreateDistribution{} }
func (m *MsgCreateDistribution) String() string { return proto.CompactTextString(m) }
func (*MsgCreateDistribution) ProtoMessage()    {}
func (*MsgCreateDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a4e4ab93b96580, []int{0}
}
func (m *MsgCreateDistribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateDistribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateDistribution.Merge(m, src)
}
func (m *MsgCreateDistribution) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateDistribution proto.InternalMessageInfo

func (m *MsgCreateDistribution) GetDistributor() string {
	if m != nil {
		return m.Distributor
	}
	return ""
}

func (m *MsgCreateDistribution) GetAuthorizedRunner() string {
	if m != nil {
		return m.AuthorizedRunner
	}
	return ""
}

func (m *MsgCreateDistribution) GetDistributionType() DistributionType {
	if m != nil {
		return m.DistributionType
	}
	return DistributionType_DISTRIBUTION_TYPE_UNSPECIFIED
}

type MsgCreateDistributionResponse struct {
}

func (m *MsgCreateDistributionResponse) Reset()         { *m = MsgCreateDistributionResponse{} }
func (m *MsgCreateDistributionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateDistributionResponse) ProtoMessage()    {}
func (*MsgCreateDistributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a4e4ab93b96580, []int{1}
}
func (m *MsgCreateDistributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateDistributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateDistributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateDistributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateDistributionResponse.Merge(m, src)
}
func (m *MsgCreateDistributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateDistributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateDistributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateDistributionResponse proto.InternalMessageInfo

type MsgCreateClaimResponse struct {
}

func (m *MsgCreateClaimResponse) Reset()         { *m = MsgCreateClaimResponse{} }
func (m *MsgCreateClaimResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateClaimResponse) ProtoMessage()    {}
func (*MsgCreateClaimResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a4e4ab93b96580, []int{2}
}
func (m *MsgCreateClaimResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateClaimResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateClaimResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateClaimResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateClaimResponse.Merge(m, src)
}
func (m *MsgCreateClaimResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateClaimResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateClaimResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateClaimResponse proto.InternalMessageInfo

type MsgRunDistributionResponse struct {
}

func (m *MsgRunDistributionResponse) Reset()         { *m = MsgRunDistributionResponse{} }
func (m *MsgRunDistributionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRunDistributionResponse) ProtoMessage()    {}
func (*MsgRunDistributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a4e4ab93b96580, []int{3}
}
func (m *MsgRunDistributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRunDistributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRunDistributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRunDistributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRunDistributionResponse.Merge(m, src)
}
func (m *MsgRunDistributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRunDistributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRunDistributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRunDistributionResponse proto.InternalMessageInfo

type MsgCreateUserClaim struct {
	UserClaimAddress string           `protobuf:"bytes,1,opt,name=user_claim_address,json=userClaimAddress,proto3" json:"user_claim_address,omitempty"`
	UserClaimType    DistributionType `protobuf:"varint,2,opt,name=user_claim_type,json=userClaimType,proto3,enum=gridnode.dispensation.v1.DistributionType" json:"user_claim_type,omitempty"`
}

func (m *MsgCreateUserClaim) Reset()         { *m = MsgCreateUserClaim{} }
func (m *MsgCreateUserClaim) String() string { return proto.CompactTextString(m) }
func (*MsgCreateUserClaim) ProtoMessage()    {}
func (*MsgCreateUserClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a4e4ab93b96580, []int{4}
}
func (m *MsgCreateUserClaim) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateUserClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateUserClaim.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateUserClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateUserClaim.Merge(m, src)
}
func (m *MsgCreateUserClaim) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateUserClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateUserClaim.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateUserClaim proto.InternalMessageInfo

func (m *MsgCreateUserClaim) GetUserClaimAddress() string {
	if m != nil {
		return m.UserClaimAddress
	}
	return ""
}

func (m *MsgCreateUserClaim) GetUserClaimType() DistributionType {
	if m != nil {
		return m.UserClaimType
	}
	return DistributionType_DISTRIBUTION_TYPE_UNSPECIFIED
}

type MsgRunDistribution struct {
	AuthorizedRunner  string           `protobuf:"bytes,1,opt,name=authorized_runner,json=authorizedRunner,proto3" json:"authorized_runner,omitempty"`
	DistributionName  string           `protobuf:"bytes,2,opt,name=distribution_name,json=distributionName,proto3" json:"distribution_name,omitempty"`
	DistributionType  DistributionType `protobuf:"varint,3,opt,name=distribution_type,json=distributionType,proto3,enum=gridnode.dispensation.v1.DistributionType" json:"distribution_type,omitempty"`
	DistributionCount int64            `protobuf:"varint,4,opt,name=distribution_count,json=distributionCount,proto3" json:"distribution_count,omitempty"`
}

func (m *MsgRunDistribution) Reset()         { *m = MsgRunDistribution{} }
func (m *MsgRunDistribution) String() string { return proto.CompactTextString(m) }
func (*MsgRunDistribution) ProtoMessage()    {}
func (*MsgRunDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_19a4e4ab93b96580, []int{5}
}
func (m *MsgRunDistribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRunDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRunDistribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRunDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRunDistribution.Merge(m, src)
}
func (m *MsgRunDistribution) XXX_Size() int {
	return m.Size()
}
func (m *MsgRunDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRunDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRunDistribution proto.InternalMessageInfo

func (m *MsgRunDistribution) GetAuthorizedRunner() string {
	if m != nil {
		return m.AuthorizedRunner
	}
	return ""
}

func (m *MsgRunDistribution) GetDistributionName() string {
	if m != nil {
		return m.DistributionName
	}
	return ""
}

func (m *MsgRunDistribution) GetDistributionType() DistributionType {
	if m != nil {
		return m.DistributionType
	}
	return DistributionType_DISTRIBUTION_TYPE_UNSPECIFIED
}

func (m *MsgRunDistribution) GetDistributionCount() int64 {
	if m != nil {
		return m.DistributionCount
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgCreateDistribution)(nil), "gridnode.dispensation.v1.MsgCreateDistribution")
	proto.RegisterType((*MsgCreateDistributionResponse)(nil), "gridnode.dispensation.v1.MsgCreateDistributionResponse")
	proto.RegisterType((*MsgCreateClaimResponse)(nil), "gridnode.dispensation.v1.MsgCreateClaimResponse")
	proto.RegisterType((*MsgRunDistributionResponse)(nil), "gridnode.dispensation.v1.MsgRunDistributionResponse")
	proto.RegisterType((*MsgCreateUserClaim)(nil), "gridnode.dispensation.v1.MsgCreateUserClaim")
	proto.RegisterType((*MsgRunDistribution)(nil), "gridnode.dispensation.v1.MsgRunDistribution")
}

func init() { proto.RegisterFile("gridnode/dispensation/v1/tx.proto", fileDescriptor_19a4e4ab93b96580) }

var fileDescriptor_19a4e4ab93b96580 = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xbb, 0x09, 0xaa, 0xd4, 0x45, 0x90, 0x74, 0x05, 0xc8, 0xb2, 0xc0, 0x0d, 0x11, 0x87,
	0x88, 0x52, 0x6f, 0x5b, 0x2a, 0x38, 0xd3, 0x20, 0x71, 0x21, 0x80, 0x2c, 0x10, 0x12, 0x97, 0x68,
	0xe3, 0x5d, 0x39, 0xab, 0xe2, 0x5d, 0xb3, 0x1f, 0x55, 0xca, 0x81, 0x37, 0x40, 0xe2, 0xc4, 0x33,
	0x71, 0xec, 0x11, 0x71, 0x40, 0x28, 0x79, 0x00, 0x6e, 0x9c, 0x91, 0x9d, 0xd8, 0x38, 0xc6, 0x41,
	0xcd, 0x81, 0x53, 0xb2, 0x33, 0xbf, 0x99, 0x1d, 0xcf, 0xfc, 0x77, 0xe0, 0xed, 0x48, 0x71, 0x2a,
	0x24, 0x65, 0x98, 0x72, 0x9d, 0x30, 0xa1, 0x89, 0xe1, 0x52, 0xe0, 0xd3, 0x03, 0x6c, 0x26, 0x7e,
	0xa2, 0xa4, 0x91, 0xc8, 0xc9, 0x11, 0xbf, 0x8c, 0xf8, 0xa7, 0x07, 0xee, 0xb5, 0x48, 0x46, 0x32,
	0x83, 0x70, 0xfa, 0x6f, 0xce, 0xbb, 0x77, 0x56, 0xa7, 0x3c, 0x4b, 0x98, 0x9e, 0x53, 0xdd, 0x8f,
	0x0d, 0x78, 0x7d, 0xa0, 0xa3, 0xbe, 0x62, 0xc4, 0xb0, 0xc7, 0x5c, 0x1b, 0xc5, 0x47, 0x36, 0x05,
	0x51, 0x07, 0x5e, 0xa6, 0xf9, 0x59, 0x2a, 0x07, 0x74, 0x40, 0x6f, 0x2b, 0x28, 0x9b, 0xd0, 0x2e,
	0xdc, 0x26, 0xd6, 0x8c, 0xa5, 0xe2, 0xef, 0x19, 0x1d, 0x2a, 0x2b, 0x04, 0x53, 0x4e, 0x23, 0xe3,
	0xda, 0x7f, 0x1c, 0x41, 0x66, 0x47, 0xaf, 0xe1, 0x36, 0x2d, 0xa5, 0x1f, 0xa6, 0x45, 0x38, 0xcd,
	0x0e, 0xe8, 0x5d, 0x3d, 0xbc, 0xeb, 0xaf, 0xfa, 0x34, 0xbf, 0x5c, 0xd1, 0xcb, 0xb3, 0x84, 0x05,
	0x6d, 0x5a, 0xb1, 0xa0, 0xa7, 0x70, 0x53, 0x5a, 0x93, 0x58, 0xe3, 0x5c, 0xea, 0x34, 0x7b, 0x5b,
	0xc7, 0x47, 0xdf, 0xbe, 0xef, 0xec, 0x47, 0xdc, 0x8c, 0xed, 0xc8, 0x0f, 0x65, 0x8c, 0x43, 0xa9,
	0x63, 0xa9, 0x17, 0x3f, 0x7b, 0x9a, 0x9e, 0xe0, 0x09, 0x1e, 0x11, 0x71, 0xb2, 0x68, 0xc3, 0xf3,
	0x2c, 0x36, 0x58, 0xe4, 0xe8, 0xee, 0xc0, 0x5b, 0xb5, 0xed, 0x08, 0x98, 0x4e, 0xa4, 0xd0, 0xac,
	0xeb, 0xc0, 0x1b, 0x05, 0xd0, 0x7f, 0x4b, 0x78, 0x5c, 0x78, 0x6e, 0x42, 0x77, 0xa0, 0xa3, 0xc0,
	0x8a, 0xda, 0xb8, 0xcf, 0x00, 0xa2, 0x22, 0xf0, 0x95, 0x66, 0x2a, 0x0b, 0x46, 0xf7, 0x20, 0xb2,
	0x9a, 0xa9, 0x61, 0x98, 0x9e, 0x86, 0x84, 0x52, 0xc5, 0xb4, 0x5e, 0x34, 0xbb, 0x6d, 0x73, 0xec,
	0xd1, 0xdc, 0x8e, 0x02, 0xd8, 0x2a, 0xd1, 0x59, 0x0b, 0x1b, 0x6b, 0xb7, 0xf0, 0x4a, 0x91, 0x36,
	0x3d, 0x76, 0x7f, 0xcd, 0x0b, 0xab, 0xd4, 0x5d, 0x3f, 0x5c, 0xb0, 0x62, 0xb8, 0xbb, 0x95, 0xe1,
	0x0a, 0x12, 0xb3, 0x5c, 0x09, 0x65, 0xc7, 0x33, 0x12, 0xb3, 0xff, 0xa7, 0x84, 0x3d, 0x88, 0x96,
	0x12, 0x87, 0xd2, 0x8a, 0x54, 0x15, 0xa0, 0xd7, 0x0c, 0x96, 0xae, 0xec, 0xa7, 0x8e, 0xc3, 0x9f,
	0x0d, 0xd8, 0x1c, 0xe8, 0x08, 0x7d, 0x80, 0xa8, 0x46, 0xfe, 0x78, 0x75, 0x29, 0xb5, 0x02, 0x71,
	0x1f, 0xae, 0x19, 0x90, 0x2b, 0x03, 0xbd, 0x83, 0xad, 0xbf, 0x54, 0x71, 0x81, 0x5c, 0x05, 0xed,
	0xee, 0x5f, 0x80, 0x5e, 0x92, 0x2a, 0xb2, 0xb0, 0x55, 0x9d, 0xf7, 0xbf, 0xaf, 0xac, 0xd0, 0xee,
	0xd1, 0x3a, 0x74, 0x7e, 0xed, 0xf1, 0x8b, 0x2f, 0x53, 0x0f, 0x9c, 0x4f, 0x3d, 0xf0, 0x63, 0xea,
	0x81, 0x4f, 0x33, 0x6f, 0xe3, 0x7c, 0xe6, 0x6d, 0x7c, 0x9d, 0x79, 0x1b, 0x6f, 0x1e, 0x94, 0x1e,
	0xec, 0x13, 0xc5, 0x29, 0x57, 0x52, 0x84, 0x63, 0xc2, 0x05, 0x2e, 0xb6, 0xd8, 0x64, 0x79, 0x8f,
	0x65, 0xaf, 0x77, 0xb4, 0x99, 0x6d, 0xb1, 0xfb, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xa0,
	0xb4, 0x55, 0x40, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateDistribution(ctx context.Context, in *MsgCreateDistribution, opts ...grpc.CallOption) (*MsgCreateDistributionResponse, error)
	CreateUserClaim(ctx context.Context, in *MsgCreateUserClaim, opts ...grpc.CallOption) (*MsgCreateClaimResponse, error)
	RunDistribution(ctx context.Context, in *MsgRunDistribution, opts ...grpc.CallOption) (*MsgRunDistributionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateDistribution(ctx context.Context, in *MsgCreateDistribution, opts ...grpc.CallOption) (*MsgCreateDistributionResponse, error) {
	out := new(MsgCreateDistributionResponse)
	err := c.cc.Invoke(ctx, "/gridnode.dispensation.v1.Msg/CreateDistribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateUserClaim(ctx context.Context, in *MsgCreateUserClaim, opts ...grpc.CallOption) (*MsgCreateClaimResponse, error) {
	out := new(MsgCreateClaimResponse)
	err := c.cc.Invoke(ctx, "/gridnode.dispensation.v1.Msg/CreateUserClaim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RunDistribution(ctx context.Context, in *MsgRunDistribution, opts ...grpc.CallOption) (*MsgRunDistributionResponse, error) {
	out := new(MsgRunDistributionResponse)
	err := c.cc.Invoke(ctx, "/gridnode.dispensation.v1.Msg/RunDistribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateDistribution(context.Context, *MsgCreateDistribution) (*MsgCreateDistributionResponse, error)
	CreateUserClaim(context.Context, *MsgCreateUserClaim) (*MsgCreateClaimResponse, error)
	RunDistribution(context.Context, *MsgRunDistribution) (*MsgRunDistributionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateDistribution(ctx context.Context, req *MsgCreateDistribution) (*MsgCreateDistributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDistribution not implemented")
}
func (*UnimplementedMsgServer) CreateUserClaim(ctx context.Context, req *MsgCreateUserClaim) (*MsgCreateClaimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserClaim not implemented")
}
func (*UnimplementedMsgServer) RunDistribution(ctx context.Context, req *MsgRunDistribution) (*MsgRunDistributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunDistribution not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateDistribution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gridnode.dispensation.v1.Msg/CreateDistribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateDistribution(ctx, req.(*MsgCreateDistribution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateUserClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateUserClaim)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateUserClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gridnode.dispensation.v1.Msg/CreateUserClaim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateUserClaim(ctx, req.(*MsgCreateUserClaim))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RunDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRunDistribution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RunDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gridnode.dispensation.v1.Msg/RunDistribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RunDistribution(ctx, req.(*MsgRunDistribution))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gridnode.dispensation.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDistribution",
			Handler:    _Msg_CreateDistribution_Handler,
		},
		{
			MethodName: "CreateUserClaim",
			Handler:    _Msg_CreateUserClaim_Handler,
		},
		{
			MethodName: "RunDistribution",
			Handler:    _Msg_RunDistribution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gridnode/dispensation/v1/tx.proto",
}

func (m *MsgCreateDistribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateDistribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateDistribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Output) > 0 {
		for iNdEx := len(m.Output) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.Output[iNdEx].Size()
				i -= size
				if _, err := m.Output[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.DistributionType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DistributionType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AuthorizedRunner) > 0 {
		i -= len(m.AuthorizedRunner)
		copy(dAtA[i:], m.AuthorizedRunner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AuthorizedRunner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Distributor) > 0 {
		i -= len(m.Distributor)
		copy(dAtA[i:], m.Distributor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Distributor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateDistributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateDistributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateDistributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateClaimResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateClaimResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateClaimResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRunDistributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRunDistributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRunDistributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateUserClaim) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateUserClaim) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateUserClaim) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UserClaimType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.UserClaimType))
		i--
		dAtA[i] = 0x10
	}
	if len(m.UserClaimAddress) > 0 {
		i -= len(m.UserClaimAddress)
		copy(dAtA[i:], m.UserClaimAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UserClaimAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRunDistribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRunDistribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRunDistribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DistributionCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DistributionCount))
		i--
		dAtA[i] = 0x20
	}
	if m.DistributionType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DistributionType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DistributionName) > 0 {
		i -= len(m.DistributionName)
		copy(dAtA[i:], m.DistributionName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DistributionName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuthorizedRunner) > 0 {
		i -= len(m.AuthorizedRunner)
		copy(dAtA[i:], m.AuthorizedRunner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AuthorizedRunner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateDistribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Distributor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AuthorizedRunner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DistributionType != 0 {
		n += 1 + sovTx(uint64(m.DistributionType))
	}
	if len(m.Output) > 0 {
		for _, e := range m.Output {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgCreateDistributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateClaimResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRunDistributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateUserClaim) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserClaimAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.UserClaimType != 0 {
		n += 1 + sovTx(uint64(m.UserClaimType))
	}
	return n
}

func (m *MsgRunDistribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AuthorizedRunner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DistributionName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DistributionType != 0 {
		n += 1 + sovTx(uint64(m.DistributionType))
	}
	if m.DistributionCount != 0 {
		n += 1 + sovTx(uint64(m.DistributionCount))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateDistribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateDistribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateDistribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Distributor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Distributor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizedRunner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizedRunner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionType", wireType)
			}
			m.DistributionType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionType |= DistributionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Output", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_x_bank_types.Output
			m.Output = append(m.Output, v)
			if err := m.Output[len(m.Output)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateDistributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateDistributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateDistributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateClaimResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateClaimResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateClaimResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRunDistributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRunDistributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRunDistributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateUserClaim) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateUserClaim: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateUserClaim: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserClaimAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserClaimAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserClaimType", wireType)
			}
			m.UserClaimType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserClaimType |= DistributionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRunDistribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRunDistribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRunDistribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizedRunner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizedRunner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistributionName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionType", wireType)
			}
			m.DistributionType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionType |= DistributionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionCount", wireType)
			}
			m.DistributionCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
